apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: my-service
images:
- name: my-service
  newName: /my-service
  newTag: a2fc8b5a92a91c2712430bda55ab58c8758a491d
